sudo: false
language: ruby
rvm:
  - "2.1.5"
before_script:
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bundle exec rspec
